export function Head(props) {
  return (
    <Head>
      <title>muho.dev</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}
