import NextHead from "next/head";

export function Head(props) {
  return (
    <NextHead>
      <title>
        {props.title && `${props.title} | `}Yazılım içerikleri | muho.dev
      </title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </NextHead>
  );
}
